gpu_devices: 0 #[0,1,2,3,4,5,6,7]
backbone_layers:
- 2
- 3
- 7
bos_token: 1
channels: 1
debug: false
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
dim: 256
encoder_depth: 6
eos_token: 2
heads: 8
max_height: 192
max_seq_len: 512
max_width: 672
min_height: 32
min_width: 32
num_layers: 4
num_tokens: 8000
pad: false
pad_token: 0
patch_size: 16
scheduler: StepLR
seed: 42
encoder_structure: hybrid
temperature: 0.2
tokenizer: ./new_pca5_tokenizer.json
is_af: True
